# Generated by Django 3.1.2 on 2021-04-19 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel', models.CharField(default='Eu mesmo.', max_length=255)),
                ('produto', models.CharField(max_length=255)),
                ('data_de_pagamento', models.DateField()),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
