# Generated by Django 3.1.2 on 2021-04-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='data_compra',
            new_name='mes_de_compra',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='data_de_pagamento',
            new_name='mes_de_pagamento',
        ),
    ]
