# Generated by Django 3.1.2 on 2021-04-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20210419_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('conta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
            ],
        ),
    ]
