# Generated by Django 3.1.4 on 2021-01-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0003_auto_20210102_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='parcelas',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
