# Generated by Django 3.1.4 on 2021-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_conta_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
