# Generated by Django 3.1.4 on 2021-01-10 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0006_usuario_ganho_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data_compra',
            field=models.DateField(default=datetime.date(2021, 1, 10)),
        ),
    ]
