# Generated by Django 3.1.4 on 2021-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0009_auto_20210110_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='responsavel',
            field=models.CharField(blank=True, default='Você mesmo', max_length=255, null=True),
        ),
    ]
