# Generated by Django 3.1.4 on 2021-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0010_conta_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='responsavel',
            field=models.CharField(blank=True, default='Eu mesmo', max_length=255, null=True),
        ),
    ]
