# Generated by Django 3.1.4 on 2021-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0011_auto_20210113_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='parcela',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
