# Generated by Django 3.1.4 on 2021-01-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0012_parcelamento_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='data_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='responsavel',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
