version: 3.8

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=oopaze
      - POSTGRES_PASSWORD=mae12345
    volumes: 
      - postgres_data: /var/lib/postgresql/data/
  
volumes:
  postgres_data: