version: '3.8'

services:
  web:
    build: .
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/web
    env_file:
      .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment: 
      - POSTGRES_DB=economize
      - POSTGRES_USER=oopaze
      - POSTGRES_PASSWORD=mae12345